### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by arbaaz** [zindi-io/zindi-runner#12]
(node:62387) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Protocol error (Emulation.setDeviceMetricsOverride): Target closed.

**Comment by rkr090** [comment]
@arbaaz Which test are you executing?

**Comment by arbaaz** [comment]
@rkr090 EarthlyTea tests, when I can click on run all tests, the browser opens up and closes.

**Comment by rkr090** [comment]
Are you passing the correct data?
https://github.com/bigbinary/zindi-electron/pull/62#issuecomment-350691487

**Comment by arbaaz** [comment]
Steps were empty.
